### PR TITLE
designed Active Group Saving and implemented the modal

### PR DESCRIPTION
**Pull request by Dallat65**
Designed active group saving page to be fully responsive.

---

Please check all that apply.

#### Checklist:

- [ ] Rebased with master
- [ ] PR Description provided
- [ ] Did you communicate these changes with the affected teams?
- [ ] Did unit tests/integration tests/E2E tests get properly added/updated?
- [ ] Is this change production-ready including testing, feature toggles, configurations, and deployment considerations?

#### Frontend Checklist:

- [ ] Is this responsive and mobile friendly?
- [ ] Did you follow the [ARIA specs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA)

#### Backend Checklist:

- [ ] Does the endpoint return the correct success/error format?

---

**Screenshots**  
_add relevant screenshots here_
Screen Shot 2024-02-27 at 04 21 41

Screen Shot 2024-02-27 at 04 18 51

---

**How to test**  
_a brief message on how to test your changes, overwrite this or write "in ticket"_

### CODE REVIEW

**Comment by KristofaJosh** [comment]
Task linked: [CU-86bxc2dtv Design the active groups page](https://app.clickup.com/t/86bxc2dtv)

**Comment by KristofaJosh** [comment]
This ticket doesn't have an association with the modal component

I have stated earlier, follow the implementation on the Account Header

**Comment by Dallat65** [comment]
Screen Shot 2024-03-01 at 21 01 10

**Review by KristofaJosh — APPROVED** [review]

**Review by pelzman — APPROVED** [review]
Remove all the unnecessary comments

**Pull request merged**
