### PR TITLE
fix: select atom element

### PR DESCRIPTION
**Pull request by Dallat65**
**Description of PR**

Fixed select button naming to CamelCase and added the dropdown icon

---

Please check all that apply.

#### Checklist:

- [ ] Rebased with master
- [ ] PR Description provided
- [ ] Did you communicate these changes with the affected teams?
- [ ] Did unit tests/integration tests/E2E tests get properly added/updated?
- [ ] Is this change production-ready including testing, feature toggles, configurations, and deployment considerations?

#### Frontend Checklist:

- [ ] Is this responsive and mobile friendly?
- [ ] Did you follow the [ARIA specs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA)

#### Backend Checklist:

- [ ] Does the endpoint return the correct success/error format?

---
**Screenshot
Screen Shot 2023-12-10 at 00 52 24
s**  
_add relevant screenshots here_

---
**Test Coverage**  
_add relevant screenshots here_

### CODE REVIEW

**Comment by KristofaJosh** [comment]
Task linked: [CU-86bwj0d3z FE - Atoms - Dropdown](https://app.clickup.com/t/86bwj0d3z)

**Review by pelzman — APPROVED** [review]

**Review by Elyzsium — DISMISSED** [review]

**Comment by KristofaJosh** [comment]
@Dallat65 where is your screenshot?

**Comment by KristofaJosh** [comment]
From the screenshot above, you'd see that the select icon does not perfectly align with the input

use the input type with password to fix the styling

**Review by KristofaJosh — CHANGES_REQUESTED** [review]
Fix styling issues

**Pull request closed without merging**
