### PR TITLE
feat-dashboard wallets

### PR DESCRIPTION
**Pull request by AnosikeChidinma**
**Description of PR**

Designed the dashboard wallets.

---

Please check all that apply.

#### Checklist:

- [x] Rebased with master
- [x] PR Description provided
- [ ] Did you communicate these changes with the affected teams?
- [ ] Did unit tests/integration tests/E2E tests get properly added/updated?
- [ ] Is this change production-ready including testing, feature toggles, configurations, and deployment considerations?

#### Frontend Checklist:

- [x] Is this responsive and mobile friendly?
- [ ] Did you follow the [ARIA specs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA)

#### Backend Checklist:

- [ ] Does the endpoint return the correct success/error format?

---

**Screenshots**  
_add relevant screenshots here_

**Test Coverage**  
_add relevant screenshots here_

### CODE REVIEW

**Comment by KristofaJosh** [comment]
Task linked: [CU-86bwt2p7j Dashboard - Wallets](https://app.clickup.com/t/86bwt2p7j)

**Review by pelzman — COMMENTED** [review]
Is there any reason you didn’t attach your screenshot or gif?


I feel it would better if you can apply separation of concern in that wallet file , like create a file that implements the Global wallet card, and another for Personal Savings etc …you can now render all inside the wallets itself , with this the wallet file won’t be too jam-packed as it is .

**Comment by Dallat65** [comment]
Nice code improvement but pls format the amount on your cards using a function the database wont store number as #5,000,0000

**Review by Dallat65 — COMMENTED** [review]
check prev comment

**Review by KristofaJosh — APPROVED** [review]
Code can be improved.

- Separation of concern

**Pull request merged**
